### PR TITLE
convert http to https

### LINKED ISSUE #13: failed to download KEGG xml/png files
Hi. When I run something similar to the following:
```pathview(gene.data=kegg_gene_list, pathway.id="hsa04110", species = 'hsa', same.layer=FALSE)```
I get this error:

```
Info: Downloading xml files for hsa04110, 1/1 pathways..
Warning: Download of hsa04110 xml file failed!
This pathway may not exist!
Info: Downloading png files for hsa04110, 1/1 pathways..
Warning: Download of hsa04110 png file failed!
This pathway may not exist!
Warning: Failed to download KEGG xml/png files, hsa04110 skipped!
```

This used to work about two weeks ago or so. I wonder if the error is related to changes on the KEGG API and similar to this:
https://github.com/YuLab-SMU/clusterProfiler/issues/470

-Thanks

### PR DESCRIPTION
**Pull request by javadnoorb**
this PR resolves #13. I tested it and it worked.

### CODE REVIEW

**Comment by LeeKamlong** [comment]
Hi, would you mind to provide the code about how to convert http?  I'm new to pathview even R ,thank a lot ><!

**Comment by javadnoorb** [comment]
Hi. Until the repo gets fixed you can just use the PR that I wrote to reinstall pathview. Try the following:
~~devtools::install_github("javnoorb/pathview")~~
```
devtools::install_github("javadnoorb/pathview")
```

**Comment by guidohooiveld** [comment]
> 



> Hi. Until the repo gets fixed you can just use the PR that I wrote to reinstall pathview. Try the following:
> 
> ```
> devtools::install_github("javnoorb/pathview")
> ```



FYI: you may have a mistake in the 'url':
For me the line of code (in the 2nd post) to install the PR did not work; however changing it a little (i.e. adapting the name of the repo) it worked!


To be clear, this works: `devtools::install_github("javadnoorb/pathview")`






**Thus, the code in 2nd post doesn't work...**
```
> devtools::install_github("javnoorb/pathview")
Error: Failed to install 'pathview' from GitHub:
  HTTP error 404.
  Not Found

  Did you spell the repo owner (`javnoorb`) and repo name (`pathview`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.

```


**... but changing it a little fixed the PR, and indeed the output of `pathview`!**
```
> devtools::install_github("javadnoorb/pathview")
Downloading GitHub repo javadnoorb/pathview@HEAD
  
  
  
   checking for file 'C:\TMP_R\Rtmpe0etNQ\remotesad44343c4b5d\javadnoorb-pathview-9f5c78b/DESCRIPTION' ...
  
   checking for file 'C:\TMP_R\Rtmpe0etNQ\remotesad44343c4b5d\javadnoorb-pathview-9f5c78b/DESCRIPTION' ... 
  
✔  checking for file 'C:\TMP_R\Rtmpe0etNQ\remotesad44343c4b5d\javadnoorb-pathview-9f5c78b/DESCRIPTION' (1.3s)

  
  
  
─  preparing 'pathview': (391ms)
   checking DESCRIPTION meta-information ...
  
   checking DESCRIPTION meta-information ... 
  
✔  checking DESCRIPTION meta-information

  
  
  
─  checking for LF line-endings in source and make files and shell scripts

  
  
  
─  checking for empty or unneeded directories

  
   NB: this package now depends on R (>= 
  
     NB: this package now depends on R (>= 3.5.0)

  
     WARNING: Added dependency on R >= 3.5.0 because serialized objects in
     serialize/load version 3 cannot be read in older versions of R.
     File(s) containing such objects:
     'pathview/data/korg.rda'
  
       'pathview/data/korg.rda'
─  building 'pathview_1.31.3.tar.gz'

  
   

'\\PC001\My Documents'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
* installing *source* package 'pathview' ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (pathview)
> 

```




**Test (using code form help page).**
```
> library(pathview)
> data(gse16873.d)
> data(demo.paths)
> 
> i <- 1
> pv.out <- pathview(gene.data = gse16873.d[, 1], pathway.id =
+                    demo.paths$sel.paths[i], species = "hsa",
+                    out.suffix = "gse16873", kegg.native = TRUE)
Info: Downloading xml files for hsa04110, 1/1 pathways..
Info: Downloading png files for hsa04110, 1/1 pathways..
'select()' returned 1:1 mapping between keys and columns
Info: Working in directory E:/000test
Info: Writing image file hsa04110.gse16873.png
> 
> str(pv.out)
List of 2
 $ plot.data.gene:'data.frame': 92 obs. of  10 variables:
  ..$ kegg.names: chr [1:92] "1029" "51343" "4171" "4998" ...
  ..$ labels    : chr [1:92] "CDKN2A" "FZR1" "MCM2" "ORC1" ...
  ..$ all.mapped: chr [1:92] "1029" "51343" "4171,4172,4173,4174,4175,4176" "4998,4999,5000,5001,23594,23595" ...
  ..$ type      : chr [1:92] "gene" "gene" "gene" "gene" ...
  ..$ x         : num [1:92] 532 919 553 494 919 919 188 432 123 77 ...
  ..$ y         : num [1:92] 124 536 556 556 297 519 519 191 704 687 ...
  ..$ width     : num [1:92] 46 46 46 46 46 46 46 46 46 46 ...
  ..$ height    : num [1:92] 17 17 17 17 17 17 17 17 17 17 ...
  ..$ mol.data  : num [1:92] 0.129 -0.404 -0.42 0.986 0.936 ...
  ..$ mol.col   : chr [1:92] "#BEBEBE" "#5FDF5F" "#5FDF5F" "#FF0000" ...
 $ plot.data.cpd : NULL
> 
> head(pv.out$plot.data.gene)
  kegg.names labels                                  all.mapped type   x   y
4       1029 CDKN2A                                        1029 gene 532 124
5      51343   FZR1                                       51343 gene 919 536
6       4171   MCM2               4171,4172,4173,4174,4175,4176 gene 553 556
7       4998   ORC1             4998,4999,5000,5001,23594,23595 gene 494 556
8        996  CDC27 996,8697,8881,10393,25847,25906,29882,51433 gene 919 297
9        996  CDC27 996,8697,8881,10393,25847,25906,29882,51433 gene 919 519
  width height   mol.data mol.col
4    46     17  0.1291987 #BEBEBE
5    46     17 -0.4043256 #5FDF5F
6    46     17 -0.4202181 #5FDF5F
7    46     17  0.9864873 #FF0000
8    46     17  0.9363018 #FF0000
9    46     17  0.9363018 #FF0000
> 

```

And in working directory, the 2 files downloaded from KEGG are present (hsa04110.png and hsa04110.xml), and a png of the pathway with the regulation of the genes overlaid (hsa04110.gse16873.png). 


hsa04110 gse16873


```
> sessionInfo()
R version 4.2.0 Patched (2022-05-12 r82348 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

Matrix products: default

Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rounding 
 
locale:
[1] LC_COLLATE=English_United States.utf8 
[2] LC_CTYPE=English_United States.utf8   
[3] LC_MONETARY=English_United States.utf8
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] pathview_1.31.3

<<snip>>
```

**Comment by javadnoorb** [comment]
Ah! Thanks! I misspelled my user ID.

**Comment by javadnoorb** [comment]
I just corrected my original post to prevent more confusion for others.

**Review by wluo1 — APPROVED** [review]
fix the bug caused by recent change in kegg rest API urls (http to https)

**Pull request merged**
